version: '3.8'
services:
  web:
    image: nginx
    ports:
      - 80:80
    networks:
      - network
  database:
    image: redis
    ports:
      - 6379:6379  
    networks:
      - network    
networks:
  network:
  